FuchsiaMeetingRoom_Script:
	call EnableAutoTextBoxDrawing
	ret

FuchsiaMeetingRoom_TextPointers:
	def_text_pointers
	dw_const FuchsiaMeetingRoomSafariZoneWorker1, TEXT_FUCHSIAMEETINGROOM_SAFARI_ZONE_WORKER1
	dw_const FuchsiaMeetingRoomSafariZoneWorker2, TEXT_FUCHSIAMEETINGROOM_SAFARI_ZONE_WORKER2
	dw_const FuchsiaMeetingRoomSafariZoneWorker3, TEXT_FUCHSIAMEETINGROOM_SAFARI_ZONE_WORKER3
	dw_const FuchsiaMeetingRoomPhoneText,         TEXT_FUCHSIAMEETINGROOM_PHONE ; marcelnote - new pay phones

FuchsiaMeetingRoomSafariZoneWorker1:
	text_far _FuchsiaMeetingRoomSafariZoneWorker1
	text_end

FuchsiaMeetingRoomSafariZoneWorker2:
	text_far _FuchsiaMeetingRoomSafariZoneWorker2
	text_end

FuchsiaMeetingRoomSafariZoneWorker3:
	text_far _FuchsiaMeetingRoomSafariZoneWorker3
	text_end

FuchsiaMeetingRoomPhoneText: ; marcelnote - new pay phones
	text_far _FuchsiaMeetingRoomPhoneText
	text_end
